/* Generated by AN DISI Unibo */ 
package it.unibo.syncer

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Syncer ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var Frequency = 600L
				var DMIN = 50
				var StartTime = 0L
				var IsPermanent = false
				var IsSonarSync = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 
						            StartTime = System.currentTimeMillis() 
						            Frequency = 700L 		//common freq
						CommUtils.outred("$name | 10s countdown...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						if(  !IsPermanent && (System.currentTimeMillis() - StartTime) > 100000  
						 ){ IsPermanent = true  
						CommUtils.outred("$name | Permanent Sync (10 sec passed)!")
						}
						if(  IsPermanent || IsSonarSync  
						 ){emit("syn", "syn($Frequency)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_work", 
				 	 					  scope, context!!, "local_tout_"+name+"_work", Frequency )  //OCT2023
					}	 	 
					 transition(edgeName="t012",targetState="work",cond=whenTimeout("local_tout_"+name+"_work"))   
					transition(edgeName="t013",targetState="handleSonar",cond=whenEvent("sonar_data"))
				}	 
				state("handleSonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                var Dist = payloadArg(0).toInt() 
								                IsSonarSync = (Dist < DMIN) 
								CommUtils.outred("$name | Sonar: $Dist | Temporary sync: $IsSonarSync")
								if(  !IsSonarSync && !IsPermanent  
								 ){forward("stop_syn", "stop_syn(0)" ,"firefly1" ) 
								forward("stop_syn", "stop_syn(0)" ,"firefly2" ) 
								forward("stop_syn", "stop_syn(0)" ,"firefly3" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
} 
