/* Generated by AN DISI Unibo */ 
package it.unibo.firefly3

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly3 ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "randomFlash"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				var X = 3
				var Y = 1
				var Frequency = java.util.Random().nextLong(500L, 1000L)
		return { //this:ActionBasciFsm
				state("randomFlash") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(100) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_randomFlash", 
				 	 					  scope, context!!, "local_tout_"+name+"_randomFlash", Frequency )  //OCT2023
					}	 	 
					 transition(edgeName="t08",targetState="randomFlash",cond=whenTimeout("local_tout_"+name+"_randomFlash"))   
					transition(edgeName="t09",targetState="syncedFlash",cond=whenEvent("syn"))
				}	 
				state("syncedFlash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("syn(FREQUENCY)"), Term.createTerm("syn(Frequency)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Frequency = payloadArg(0).toLong()  
								CommUtils.outyellow("$name | Synchronizing to $Frequency ms")
						}
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						delay(100) 
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t110",targetState="syncedFlash",cond=whenEvent("syn"))
					transition(edgeName="t111",targetState="randomFlash",cond=whenDispatch("stop_syn"))
				}	 
			}
		}
} 
